### ISSUE TITLE
grunt-jsdoc not working on my mac(10.9)

### ISSUE THREAD

**Issue by jatinder85** [krampstudio/grunt-jsdoc#61]
sh-3.2# grunt jsdoc --force
Running "jsdoc:dist" (jsdoc) task

> > An error occurs in jsdoc process:
> > Exception in thread "main"
> > Warning: jsdoc failure Used --force, continuing.
> > An error occurs in jsdoc process:
> > java.lang.NoClassDefFoundError: org/mozilla/javascript/tools/shell/Main
> > Caused by: java.lang.ClassNotFoundException: org.mozilla.javascript.tools.shell.Main
> >  at java.net.URLClassLoader$1.run(URLClassLoader.java:202)
> >  at java.security.AccessController.doPrivileged(Native Method)
> >  at java.net.URLClassLoader.findClass(URLClassLoader.java:190)
> >  at java.lang.ClassLoader.loadClass(ClassLoader.java:306)
> >  at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:301)
> >  at java.lang.ClassLoader.loadClass(ClassLoader.java:247)
> > Warning: jsdoc failure Used --force, continuing.
> > jsdoc terminated
> > Warning: jsdoc failure Used --force, continuing.
> > sh-3.2#
